AWS_ACCESS_KEY: "AKIARBHI2FVTCSM4XBUG"
AWS_SECRET_KEY: "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"
AWS_BUCKET:     "my-grams-bucket"
AWS_REGION:     "us-east-1"

SECRET_KEY: 'sk_test_Egyo3I3nQI2cq0rYtUeSvadY006gOjQhlh'
PUBLISHABLE_KEY: 'pk_test_ZVZHwFn0glApjU1fvgjTaxCv00gpRyVcbB'